import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import { Title, DiscordBtn, PinkText, PinkCard, Button, Logo } from "../styles/index.tw";

import pika from "../assets/pikadao.gif";

const code = `BlossomDAO = {
  "About": {
      "domain": ".eth",
      "membership": "NFT",
      "desc": "Developers building out the Metaverse"
  }
};`;

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen overflow-hidden">
      <Head>
        <title>Blossom DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex-grow mt-60">
        <div className="flex justify-between items-center max-w-7xl m-auto">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 flex-1">
            <h1 className="text-5xl font-bold">Welcome to</h1>
            <Title className="text-5xl">BlossomDAO</Title>
            <p className="my-10">
              Where blockchain and Web3 developers from all levels of expertise learn, build and ship together under one
              DAO!
            </p>
            <div className="w-40">
              <a href="https://discord.gg/9aTgw2hy6K" rel="noreferrer" target="_blank">
                <DiscordBtn>Join the DAO →</DiscordBtn>
              </a>
            </div>
          </div>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 flex-1">
            <Image src={pika} alt="" />
          </div>
        </div>

        <div className="flex flex-col justify-center items-center max-w-2xl m-auto my-36">
          <div>
            <h1 className="text-5xl font-bold">
              About <PinkText>Us</PinkText>
            </h1>
          </div>
          <div className="text-center">
            <p className="mb-2 text-lg mt-5">
              Building out the <PinkText>Metaverse</PinkText> while also having fun!
            </p>
            <p className="text-gray-500">
              We are a group of developers from across the Metaverse that come up with innovative ideas for the
              blockchain and Web3 space. We form dynamic teams that then build out these products and deploy them under
              the domain &quot;BlossomDAO&quot;.
            </p>

            <p className="text-gray-500 mt-4">
              We love to learn, build and ship products together. Anyone is free to join.
            </p>

            <div className="shadow-xl rounded-lg p-10">
              <pre className="text-left">
                <code
                  dangerouslySetInnerHTML={{
                    __html: code
                  }}
                ></code>
              </pre>
            </div>
          </div>
        </div>

        <div className="flex flex-col justify-center items-center max-w-2xl m-auto my-36">
          <div>
            <h1 className="text-5xl font-bold">
              Comm<PinkText>unity</PinkText>
            </h1>
          </div>
          <div className="text-center mt-10">
            <p className="text-gray-500">
              We mainly hang out on Discord, but we have a bunch of other resources over there for you to enjoy as well!
            </p>

            <p className="text-gray-500 mt-4">
              This is where our teams meet, our community chats and our ideas are born!
            </p>

            <div className="w-40 m-auto mt-10">
              <a href="https://discord.gg/9aTgw2hy6K" rel="noreferrer" target="_blank">
                <DiscordBtn>Discord</DiscordBtn>
              </a>
            </div>

            <div className="mt-20 justify-center align-center flex">
              <iframe
                src="https://discord.com/widget?id=893023756849672223&theme=dark"
                width="500"
                height="500"
                allowtransparency="true"
                frameBorder="0"
                sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"
              ></iframe>
            </div>
          </div>
        </div>

        <div className="flex flex-col justify-center items-center max-w-3xl m-auto my-36">
          <div>
            <h1 className="text-5xl font-bold">
              <PinkText>Contact</PinkText> Us
            </h1>
          </div>
          <div className="text-center mt-10">
            <p className="text-gray-500">
              If you need to send us an important email, or just want to chat to us, we got you!
            </p>

            <p className="text-gray-500 mt-4">We are currently using a mailing service called ETHmail, cool right !</p>

            <PinkCard className="mt-20 rounded-lg px-20 py-10 text-left">
              <h2 className="text-xl leading-none font-bold">
                For any business enquiries or client work, we will respond as soon as we can!
              </h2>
              <p className="mt-4 mb-10">Excited to meet you :)</p>
              <a href="https://ethmail.cc/" rel="noreferrer" target="_blank">
                <Button className="w-28">Ethmail →</Button>
              </a>
            </PinkCard>
          </div>
        </div>

        <hr />
      </main>

      <footer className="flex flex-grow my-14 mx-auto">
        <div className="flex flex-col justify-between m-auto flex-1">
          <div className="justify-start px-4 sm:px-6 md:px-8 flex-1">
            <Logo>🌸</Logo>
          </div>
          <div className="px-4 sm:px-6 md:px-8 flex-1">BlossomDAO</div>
          <div className="mx-auto mt-6 text-sm text-gray-500 px-4 sm:px-6 md:px-8 flex-1">
            Copyright © 2021 BlossomDAO.eth All rights reserved.
          </div>
        </div>
        <div className="flex flex-col justify-between m-auto flex-1">
          <div className="px-4 sm:px-6 md:px-8 flex-1">Legal</div>
          <div className="px-4 sm:px-6 md:px-8 flex-1">Terms of Service</div>
          <div className="px-4 sm:px-6 md:px-8 flex-1">Privacy Policy</div>
        </div>
        <div className="flex justify-between items-center m-auto flex-1">section 3</div>
      </footer>
    </div>
  );
}
